//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    public partial class WebForm
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.Label Label1;
        protected global::System.Web.UI.WebControls.Label cus_name;
        protected global::System.Web.UI.WebControls.TextBox txt_name;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
        protected global::System.Web.UI.WebControls.RegularExpressionValidator RegularExpressionValidator1;

        protected global::System.Web.UI.WebControls.Label address;
        protected global::System.Web.UI.WebControls.TextBox txt_address;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator2;

        protected global::System.Web.UI.WebControls.Label p_code;
        protected global::System.Web.UI.WebControls.TextBox txt_pcode;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator3;

        protected global::System.Web.UI.WebControls.Label quentity;
        protected global::System.Web.UI.WebControls.TextBox txt_quentity;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator4;

        protected global::System.Web.UI.WebControls.Label Label12;
        protected global::System.Web.UI.WebControls.Label c_type;
        protected global::System.Web.UI.WebControls.DropDownList DropDownList1;

        protected global::System.Web.UI.WebControls.Label c_number;
        protected global::System.Web.UI.WebControls.TextBox txt_card_num;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator5;

        protected global::System.Web.UI.WebControls.Label ex_date;
        protected global::System.Web.UI.WebControls.TextBox txt_exdate;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator6;

        protected global::System.Web.UI.WebControls.Label cvc_num;
        protected global::System.Web.UI.WebControls.TextBox txt_cvc;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator7;

        protected global::System.Web.UI.WebControls.Label card_name;
        protected global::System.Web.UI.WebControls.TextBox fname;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator8;
        protected global::System.Web.UI.WebControls.TextBox lname;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator9;

        protected global::System.Web.UI.WebControls.Button Submit1;
        protected global::System.Web.UI.WebControls.Button Reset1;
    }
}
